### ISSUE TITLE
Inquiry about Release Plans for Checkpoints

### ISSUE THREAD

**Issue by RuihanLu** [AkiraHero/diffindscene#1]
Hi,

First of all, I would like to express my gratitude for the solid work you have done. Congratulations on having your work accepted at CVPR!

I am particularly interested in the checkpoints used in your project. Do you have any plans to release these checkpoints? Access to them would be incredibly beneficial for further research and experimentation.

Thank you again for your contributions to the field. Looking forward to your response.

Best,
Ruihan

**Comment by RuihanLu** [comment]
And I am very interested in the computational resources required and the training duration for your method. I couldn't find this information in your paper or supplementary materials. Could you kindly share these details?

**Comment by AkiraHero** [comment]
@RuihanLu  Thanks for your attention. All checkpoints and the starting guide have been updated.
