### ISSUE TITLE
Good Jobs. Can you provide start guide? I encounter some package loss and conflicts when using dev_env.yml 

### ISSUE THREAD

**Issue by miyapeng** [AkiraHero/diffindscene#2]
Good Jobs. Can you provide start guide? I encounter some package loss and conflicts when using dev_env.yml 
just like Pip subprocess error:
ERROR: Could not find a version that satisfies the requirement diff-gaussian-rasterization==0.0.0 (from versions: none)
ERROR: No matching distribution found for diff-gaussian-rasterization==0.0.0 and so on
Thank you!

**Comment by RuihanLu** [comment]
Giving my solution as a reference:

Run `conda env update -f dev_env.yml` multiple times, commenting out the packages that appear in the error report from dev_env.yml until the command runs successfully.

Then just go ahead and install those commented packages manually. Those packages can be found on GitHub with detailed tutorials on how to install them.

**Comment by miyapeng** [comment]
Thank you. I solve the problem finally. The paper have not release the checkpoint  , have you train?I wander how many GPUs and how much memoey needed?

**Comment by RuihanLu** [comment]
I haven't started training yet because data processing is slow. I'm still using Blender to remesh the scene to be a watertight mesh. There are about 6,000 scenes. I've run it for 50 hours so far and finished extracting 3000 scenes.

**Comment by miyapeng** [comment]
That really spends long time! will you release your processed data? Thank you very much
